database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "senha"
  dbName: "minecraft"
invite:
  maxInvitationTime: 5 # * minutes
  maxAllyInvitationTime: 1 # * dias
redis:
  host: localhost
  port: 6379
  database: 1
kill:
  points: 10
  neutralStealPoints: 10 # 10%
  enemyStealPoints: 20 #20%
war:
  enemy-points: 10
  neutral-points: 5
  ally-points: 0
clan:
  core-price: 150
  anti-core-price: 100