name: factions
version: '1.0'
main: org.quintilis.factions.Factions
api-version: '1.21'
folia-supported: true

commands:
    clan:
        description: Main clan command
        aliases: [c]
        usage: /clan [subcommand]
    home:
        description: Teleport home command
        aliases: [h]
        usage: /home

dependencies:
    server:
        FancyNpcs:
            load: BEFORE
            required: false
            join-classpath: true
        PlaceholderAPI:
            load: BEFORE
            required: true
            join-classpath: true