name: factions
version: '1.0'
main: org.quintilis.factions.Factions
api-version: '1.21'

commands:
    clan:
        description: Main clan command
        aliases: [c]
        usage: /clan [subcommand]

dependencies:
    server:
        FancyNpcs:
            load: BEFORE
            required: false
            join-classpath: true